### ISSUE TITLE
`ember-modifier@3.2.5` erroneously reporting deprecations

### ISSUE THREAD

**Issue by jknight12882** [ember-modifier/ember-modifier#282]
Just installed the latest version of `ember-modifier` and converted my `{{modifier}}` to use the patterns. However, even though I'm not using any of the deprecated methods, I still get a spew of deprecation logs in my console output. Here's an example of one of my modifiers
```javascript
import { registerDestructor } from '@ember/destroyable';
import Modifier from 'ember-modifier';
import tippy from 'tippy.js';

const cleanup = (instance) => {
  instance.tippy?.destroy();
};

class TippyModifier extends Modifier {
  tippy = null;

  constructor() {
    super(...arguments);
    registerDestructor(this, cleanup);
  }

  modify(element, _, { content }) {
    cleanup(this);

    if (!content) {
      this.tippy = null;
      return;
    }

    this.tippy = tippy(element, {
      content,
    });
  }
}

export default TippyModifier;
```
As you can see, no deprecated methods. However, I get every single deprecation warning logged to console for every single instance of the modifier on the page (which is a lot)

**Comment by danr1979** [comment]
I am experiencing the same issue.

**Comment by bertdeblock** [comment]
Seeing the same thing as well. AFAICT I've done everything needed to get rid of the deprecations, but my console is still flooded with deprecations.

**Comment by chriskrycho** [comment]
I *suspect* we have a deprecation predicate inverted somewhere. 🤔

**Comment by chriskrycho** [comment]
Should be resolved in [v3.2.6](https://github.com/ember-modifier/ember-modifier/releases/tag/v3.2.6) (via #283).

**Comment by bertdeblock** [comment]
[v3.2.6](https://github.com/ember-modifier/ember-modifier/releases/tag/v3.2.6) doesn't seem to completely resolve this issue (at least for me).
I'm still seeing deprecation warnings in my console for issues I have already fixed.
Experiencing this here: https://github.com/bertdeblock/ember-style-modifier/tree/resolve-ember-modifier-deprecations

**Comment by bertdeblock** [comment]
https://github.com/ember-modifier/ember-modifier/pull/288 seems to fix it for me.

**Comment by danr1979** [comment]
> Should be resolved in [v3.2.6](https://github.com/ember-modifier/ember-modifier/releases/tag/v3.2.6) (via #283).

This fixed it for me.  Thank you.

**Comment by chriskrycho** [comment]
For anyone following along: I just released v3.2.7, incorporating @bertdeblock's fixes in #288 (thank you!).
