### ISSUE TITLE
Local modifiers not working correctly

### ISSUE THREAD

**Issue by amk221** [ember-modifier/ember-modifier#78]
Firstly, apologies if this is being raised too soon. I heard about local modifiers on the grape vine, and I'm not aware of how far along they officially are.

I've created a very basic [demo app](https://github.com/amk221/-ember-modifier-install/blob/master/app/components/my-component.js#L9) that compares local modifiers to global ones, because I think there is something wrong with the install/update/destroy hooks.

Here is a video of the demo app: https://share.getcloudapp.com/7KuPbQLR.

**Comment by amk221** [comment]
```
modifier(() => {
  console.log('setup');
  return () => console.log('teardown');
})
```
Global:

1. setup
2. teardown
3. setup

Local

1. setup
2. setup
3. teardown

**Comment by pzuraq** [comment]
Can you confirm the bug exists on the latest beta? There have been some bugs with dynamic modifiers and we've been landing patches, so just want to make sure this is still an issue.

**Comment by amk221** [comment]
Confirm it still exists with `3.27.0-beta.3`

**Comment by pzuraq** [comment]
The issue is likely coming from this line: https://github.com/glimmerjs/glimmer-vm/blob/master/packages/@glimmer/manager/lib/public/modifier.ts#L116

With the older versions of modifier manager capabilities, we eagerly reified arguments whenever a new modifier was created in order to provide it args. This is tracked for dynamic modifiers, and results in us creating a new instance of the modifier.

For the `api` version of the bug, it's a little less clear. Because you are using `(hash)` to create the API, you _are_ creating a new reference to a new hash each time the value changes, with the same modifier definition. This results in destroying the modifier and recreating it, because according to autotracking something changed, even though the _definition_ did not.

This opens up the question: If the definition is the same, should we keep the instance?

**Comment by amk221** [comment]
Potentially fixed by https://github.com/ember-modifier/ember-modifier/pull/63

**Comment by chriskrycho** [comment]
@amk221 can you let me know if (a) this is still happening on Ember 3.28 LTS or any 4.x release and (b) if switching to the new `{ eager: false }` variant introduced in v3.2.0 of this library resolves it?

**Comment by amk221** [comment]
Yes, it does fix the the ordering problem mentioned [here](https://github.com/ember-modifier/ember-modifier/issues/78#issuecomment-819020884).  I don't think it fixes the yielded versions of a modifier, but from the above convo - that seems to be a separate question about what should happen.
thanks!

**Comment by chriskrycho** [comment]
Thanks very much, @amk221! I'll chat about this with some of the other Framework folks as we work on emberjs/rfcs#811. My own intuition is that the current behavior is correct (it's the easiest to explain in terms of normal auto-tracking semantics), but others may disagree!

**Comment by chriskrycho** [comment]
@amk221 I'm going to go ahead close this as I *believe* the semantics here are now "working as intended", though certainly a bit of a corner case we need to help people be aware of (not just for modifiers, either!). Thanks again for the report.
